<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="ghgf-PC" name="tests.slave_web.tm.Slave_TMInterventionUniqueTests" tests="2" failures="0" timestamp="05 Nov 2018 08:35:16 GMT" time="925.337" errors="1">
  <testcase name="verifyUniqueIntervention" time="0.000" classname="tests.slave_web.tm.Slave_TMInterventionUniqueTests">
    <skipped/>
  </testcase> <!-- verifyUniqueIntervention -->
  <testcase name="setUp" time="925.337" classname="tests.slave_web.tm.Slave_TMInterventionUniqueTests">
    <error type="java.lang.Exception" message="no email found">
      <![CDATA[java.lang.Exception: no email foundat utilities.ReadingEmails.getMailBody(ReadingEmails.java:172)at tests.slave_web.tm.Slave_TMInterventionUniqueTests.setAppointment(Slave_TMInterventionUniqueTests.java:106)at tests.slave_web.tm.Slave_TMInterventionUniqueTests.setUp(Slave_TMInterventionUniqueTests.java:72)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- setUp -->
</testsuite> <!-- tests.slave_web.tm.Slave_TMInterventionUniqueTests -->
