<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ghgf-PC" name="tests.company_Admin.tm.TM_CA_AppointmentTest" tests="5" failures="1" timestamp="19 Sep 2018 10:28:52 GMT" time="448.613" errors="0">
  <testcase name="updateCompanyAdminAppointment" time="69.319" classname="tests.company_Admin.tm.TM_CA_AppointmentTest"/>
  <testcase name="listOfComapnyAdminAppointment" time="118.615" classname="tests.company_Admin.tm.TM_CA_AppointmentTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	view button for 09-20-2018 15:58 status not matched expected [true] but found [false],
	update button for 09-20-2018 15:58 status not matched expected [true] but found [false],
	cancel button for 09-20-2018 15:58 status not matched expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:view button for 09-20-2018 15:58 status not matched expected [true] but found [false],update button for 09-20-2018 15:58 status not matched expected [true] but found [false],cancel button for 09-20-2018 15:58 status not matched expected [true] but found [false]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at tests.company_Admin.tm.TM_CA_AppointmentTest.listOfComapnyAdminAppointment(TM_CA_AppointmentTest.java:267)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- listOfComapnyAdminAppointment -->
  <testcase name="viewCompanyAdminAppointment" time="23.553" classname="tests.company_Admin.tm.TM_CA_AppointmentTest"/>
  <testcase name="cancelCompanyAdminAppointment" time="185.203" classname="tests.company_Admin.tm.TM_CA_AppointmentTest"/>
  <testcase name="createCompanyAdminNewAppointment" time="51.923" classname="tests.company_Admin.tm.TM_CA_AppointmentTest"/>
</testsuite> <!-- tests.company_Admin.tm.TM_CA_AppointmentTest -->
